title: Amiyah Stephens Portfolio
description: A collection of my projects and accomplishments.
url: "https://miyahhs.github.io" # e.g., https://yourname.github.io
baseurl: "" # if you use a project site, set like "/project"
author:
  name: Amiyah Stephens
  email: miyahs121@gmail.com
  # social handles used by SEO tag
  twitter: ""
  instagram: "miyahts"
  github: "miyahhs"
  linkedin: ""

permalink: /:categories/:title/
paginate: 5
paginate_path: "/page:num/"
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  posts:
    output: true
  theme: null

# Theme settings (used by includes/layouts)
theme_settings:
  show_nav_social: true
  show_post_dates: true
  accent: "pink"

# Build
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .gitignore
